package Interfaces;

import cartas.Carta;
import cartas.CartaMazo;
import com.google.gson.JsonObject;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import jugadoruno.JugadorUNO;

/**
 *
 * @author marti
 */
public class Interfaz extends javax.swing.JFrame {

    public static String nombre;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    private List<cartas.Carta> manoJugador = new ArrayList<>();
    boolean tuTurno;

    jugadoruno.JugadorUNO Jugador;

    public Interfaz() {

        initComponents();
        //pedirHost(); 
        //pedirPuerto();
        //pedirNombre();
        tuTurno = false;
        btnRobar.setEnabled(false);
        btnUno.setEnabled(false);

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        System.out.println("Construyendo Interfaz de Juego...");

    }

    public void setJugador(JugadorUNO Jugador) {
        this.Jugador = Jugador;
        ListaCartasComboBox(Jugador.getMano());
    }

    public void setManoJugador(List<cartas.Carta> mano) {
        this.manoJugador = mano;
    }

    public void ListaCartasComboBox(List<cartas.Carta> mano) {
        //agrega cartas a la mano del jugador
        //listCartas.removeAllItems();

        // linea 1
        DefaultComboBoxModel<cartas.Carta> modelo = new DefaultComboBoxModel<>();
        // linea 2
        //listCartas.setModel(modelo);

        System.out.println("Sin cartas");

        for (cartas.Carta c : this.Jugador.getMano()) {
            modelo.addElement(c);

        }

        System.out.println("Con cartas");

        listCartas.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider2 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        btnRobar = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        listCartas = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNotificacion = new javax.swing.JLabel();
        btnAzul = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnRojo = new javax.swing.JButton();
        btnAmarillo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        IblColor = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel3.setText("Jugadores");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNO MULTIJUGADOR");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        btnRobar.setBackground(new java.awt.Color(51, 51, 255));
        btnRobar.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnRobar.setForeground(new java.awt.Color(255, 255, 255));
        btnRobar.setText("Robar Carta");
        btnRobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRobarActionPerformed(evt);
            }
        });

        btnUno.setBackground(new java.awt.Color(255, 0, 0));
        btnUno.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnUno.setForeground(new java.awt.Color(255, 255, 255));
        btnUno.setText("Enviar jugada");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel7.setText("lISTA DE CARTAS");

        listCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCartasActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel1.setText("NOTIFICACIONES");

        lblTurno.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        lblTurno.setText("Esperando que se inicie el juego....");

        jLabel4.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel4.setText("TURNO");

        lblNotificacion.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        lblNotificacion.setText("- Tu");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(jLabel4))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel1))
                                .addComponent(lblNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNotificacion)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnAmarillo.setText("Amarillo");
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRobar)
                        .addGap(38, 38, 38)
                        .addComponent(btnUno))
                    .addComponent(listCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAzul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRojo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAmarillo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAzul)
                    .addComponent(btnVerde)
                    .addComponent(btnRojo)
                    .addComponent(btnAmarillo))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRobar)
                    .addComponent(btnUno))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Cartta");

        lblInfo.setBackground(new java.awt.Color(255, 51, 51));
        lblInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblInfo.setText("n               ");

        IblColor.setBackground(new java.awt.Color(255, 0, 0));
        IblColor.setForeground(new java.awt.Color(255, 0, 0));
        IblColor.setText(" nmmn ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(IblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(IblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(346, 346, 346))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CambioTurno(String Turno) {
        lblTurno.setText("Turno : " + Turno);
        btnRobar.setEnabled(false);
        btnUno.setEnabled(false);
    }

    public void TuTurno() {
        lblTurno.setText("Tu turno");
        btnRobar.setEnabled(true);
        btnUno.setEnabled(true);
    }

    private void btnRobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRobarActionPerformed
        // TODO add your handling code here:

        JsonObject mensaje = new JsonObject();
        mensaje.addProperty("Tipo", "Robar");

        String mesj = mensaje.toString();
        Jugador.enviarMensaje(mesj);


    }//GEN-LAST:event_btnRobarActionPerformed

    private void listCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCartasActionPerformed
        // seleccion de carta, de jugador
        cartas.Carta seleccionada = (cartas.Carta) listCartas.getSelectedItem();

        if (seleccionada != null) {
            System.out.println("Carta seleccionada: " + seleccionada);
        }

    }//GEN-LAST:event_listCartasActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed

        /* 
        
        1. Buscar la carta que tiene como idCartActual
        2. evaluar que la carta que eligio el jugador, tenga el color, el numero o 
           sea un comodin, de lo contrario mandarle un mesnaje al usuario y no enviar la carta 
        
        
         */
        JsonObject msj = new JsonObject();
        msj.addProperty("Tipo", "Jugada");

        cartas.Carta seleccionada = (cartas.Carta) listCartas.getSelectedItem();

        if (seleccionada == null) {
            JOptionPane.showMessageDialog(null, "Selecciona una carta, hdtpm",
                    "Pendejo",
                    JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        Carta cartaActual = Jugador.getCartaMesa();

        System.out.println("Carta seleccionada: " + seleccionada);
        manoJugador.remove(seleccionada);/*Elimina carta de la mano del jugador*/
        listCartas.removeItem(seleccionada);/*Elimina la carta del comboBoc*/
        msj.addProperty("Carta", seleccionada.getId_carta());

        String mensaje = msj.toString();
        
        Jugador.enviarMensaje(mensaje);

        boolean esValida = false;

        // si no tiene nada dentro de accion, en la carta, 
        if (seleccionada.getAccion() != null) {
            if (seleccionada.getAccion().equals("comodin")
                    || seleccionada.getAccion().equals("+4")) {
                esValida = true;
            }
        }


    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAmarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblColor;
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnRobar;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNotificacion;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JComboBox<cartas.Carta> listCartas;
    // End of variables declaration//GEN-END:variables
    public String pedirHost() {
        return JOptionPane.showInputDialog(this, "Ingresa la IP del servidor:", "localhost");
    }

    public int pedirPuerto() {

        var s = JOptionPane.showInputDialog(this, "Puerto de conexión:", "3003");
        try {
            return Integer.parseInt(s);
        } catch (Exception e) {
            return 3003;
        }

    }

    /*
    public String pedirNombre(){
        var s = JOptionPane.showInputDialog(this,"Tu nombre de jugador:","Jugador");
        return (s==null || s.isBlank())? "Jugador" : s.trim();
    }

    public void mostrarInfo(String msg){ 
        JOptionPane.showMessageDialog(this,msg,"Información",JOptionPane.INFORMATION_MESSAGE); 
    }

    public void mostrarError(String msg){ 
        JOptionPane.showMessageDialog(this,msg,"Error",JOptionPane.ERROR_MESSAGE); 
    }
     */
    public void tuTurno() {
        btnRobar.setEnabled(true);
        btnUno.setEnabled(true);
        lblTurno.setText("Tu turno");

    }

    public void iniciarJuego() {

        lblNotificacion.setText("El juego ha iniciado");
        //JOptionPane.showConfirmDialog(null, "Ya iniciow " + this.Jugador.getMano().size());

        //JOptionPane.showMessageDialog(null, "" + Jugador.getCartaActual());
        System.out.println("Dentro de iniciarJuego");

        ListaCartasComboBox(Jugador.getMano());

    }

    public void actualizarCartaMesa(cartas.Carta carta) {

        if (carta == null) {
            IblColor.setText("Carta en mesa: (ninguna)");
            return;
        }

        String texto;

        //si es una carta de numero
        if (carta.getAccion() == null) {
            texto = "Carta en mesa: " + carta.getColor() + " " + carta.getValor();
        } //Ssi es una carta de acción
        else {
            texto = "Carta en mesa: " + carta.getColor() + " " + carta.getAccion();
        }

        IblColor.setText(texto);
        jLabel5.setText("Color: " + carta.getColor());
        lblInfo.setText("Valor: " + carta.getValor());

    }

    public void cambioTurno(String turno) {
        btnRobar.setEnabled(false);
        btnUno.setEnabled(false);

        lblTurno.setText("Turno de " + turno);
    }

    public void notificacion(String not) {
        lblNotificacion.setText(not);
    }
}
